Homework 2
Radium84/java-reboot pull request #2
Opened 2023-10-21 08:51 UTC by Radium84

Реализовал класс для чтения из бд, но не стал под него делать тесты, это имхо уже избыточно. Хотелось просто посмотреть работу с двумя слабосвязанными ресурсами через интерфейс

2023-10-28 11:52 UTC, Radium84 commented
@rsmitt проверь пожалуйста

2023-10-28 14:04 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/OutputData.java
> +        writer.close();
у вас ресурс не закроется если произойдет ошибка. Оберните в try with resources но без catch

2023-10-28 14:08 UTC, rsmitt requested changes
прошу поправить в коде потенциальная утечка памяти

2023-10-29 08:25 UTC, merged

2023-11-01 18:48 UTC, Radium84 commented on module02/src/main/java/ru/sberbank/edu/OutputData.java
> +        writer.close();
@rsmitt исправил. Поскольку апрув стоял, сразу вмержил. Измени у себя в файлике cr на ок)